version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: BlogApp
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: '--default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      - blog-network

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: blog-backend
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-container:3306/BlogApp
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    restart: always
    networks:
      - blog-network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: blog-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - blog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - blog-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    ports:
      - "5000:5000"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - blog-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  elasticsearch-data:
    driver: local
